[tool.poetry]
name = "midi-to-arduino"
version = "0.1.0"
description = ""
authors = ["Issac Liu <issac@matchaflavored.site>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
